framework:
    messenger:
        transports:
            sync: 'sync://'
            tasting:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_DSN)%'
                options:
                    exchange:
                        name: tasting
                        type: direct
                        default_publish_routing_key: tasting
                    queues:
                        tasting:
                            binding_keys: [tasting]
            tasting_from_external:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_DSN)%'
                serializer: EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Serializer\ExternalMessageSerializer
                options:
                    exchange:
                        name: tasting_from_external
                        type: direct
                        default_publish_routing_key: tasting_from_external
                    queues:
                        tasting:
                            binding_keys: [tasting_from_external]
            tasting_to_bottle_inventory:
                dsn: '%env(MESSENGER_TRANSPORT_TASTING_TO_BOTTLE_INVENTORY_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: bottle_inventory_from_external
                        type: direct
                        default_publish_routing_key: bottle_inventory_from_external
                    queues:
                        tasting:
                            binding_keys: [bottle_inventory_from_external]
        routing:
            'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Message\InvitationCreatedMessage': tasting
            'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Message\InvitationStatusChangedInterface': tasting
            'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Message\CreateSheetWhenInvitationIsAcceptedMessage': tasting
            'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Message\CreateSheetWhenTastingIsCreatedMessage': tasting
            'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Message\TastingDeletedMessage': tasting

            'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\Message\CreateBottleForParticipantWhenInvitationIsAcceptedMessage': tasting_to_bottle_inventory

when@test:
    framework:
        messenger:
            transports:
                tasting: 'test://'
                tasting_from_external:
                    dsn: 'test://'
                    serializer: messenger.transport.native_php_serializer
                tasting_to_bottle_inventory:
                    dsn: 'test://'
                    serializer: messenger.transport.native_php_serializer

            routing:
                'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\ExternalMessage\UserCreatedMessage': tasting_from_external
                'EmpireDesAmis\Tasting\Infrastructure\Symfony\Messenger\ExternalMessage\BottleTastedMessage': tasting_from_external